version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map container's 3000 to host's 3001
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/dataset-platform
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - AZURE_API_KEY=api_key
      - AZURE_BASE_URL=https://instance_name.openai.azure.com/openai/deployments
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 